### PR TITLE
Fixed hardcoded PDU length (1500) which is now configurable

### LINKED ISSUE #34: only first 1500 bytes from large UDP datagrams is copied
I am working with traffic from application which sends UDP datagrams longer than 1500 Bytes so they are fragmented in IP layer.

in **samplicate.c** PDU_SIZE is fixed to 1500 [here](https://github.com/sleinen/samplicator/blob/7b4e009696bc53c6424e9c8eb039d68126488c87/samplicate.c#L40)
`#define PDU_SIZE 1500`

result of which - maximum 1500 bytes from buffer is copied and no warning nor error is thrown in case of longer UDP datagram.

I see that further there is some test that should catch longer datagram:
```
if ((n = recvfrom (ctx->fsockfd, (char*)fpdu, sizeof (fpdu), 0, (struct sockaddr *) &remote_address, &addrlen)) == -1) {
  fprintf (stderr, "recvfrom(): %s\n", strerror(errno));
  exit (1);
}
if (n > PDU_SIZE) {
  fprintf (stderr, "Warning: %d excess bytes discarded\n", n-PDU_SIZE);
  n = PDU_SIZE;
}
```

But at least in my case (kernel 2.6.18) it fails to catch it.
I think the reason is lack of `MSG_TRUNC` flag in `recvfrom()` call for modern kernels (since 2.2).

My workaround was changing PDU_SIZE to larger value, and it solved problem for my **long UDP** case but not sure if it won't broke something else - for example TCP handling.

### PR DESCRIPTION
**Pull request by pangorgo**
fixes #34 
Deleted PDU_SIZE contant and added configurable option instead.
Added MSG_TRUNC flag to recvfrom, to report datagram truncation

### CODE REVIEW

File: samplicate.c [hunk 1]
```diff
@@ -318,7 +316,7 @@ static int
 samplicate (ctx)
      struct samplicator_context *ctx;
 {
-  unsigned char fpdu[PDU_SIZE];
+  unsigned char fpdu[ctx->pdulen];
```
Comment (sleinen) [inline samplicate.c]: At first I was worried about the portability of this.  When I developed in C (a long time ago), only GCC allowed such computed array sizes for automatic variables.  According to https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html it is supported by ISO C99.  I don't know how widely that is supported.  Hopefully all compilers that people are likely to use will understand this.

**Comment by sleinen** [comment]
Thanks for your patch! It looks very clean and thorough.
